# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lv8EupToOrCkKkkjRAGTfQDpXSZyoG3W
"""

import re
import streamlit as st

def clean_number_patterns(phone):
    original = phone.strip()

    # Remove all non-digit characters except "+"
    only_digits_plus = re.sub(r"[^\d+]", "", original)

    # Extract country code (up to 4 digits after "+")
    match = re.match(r"^\+?(\d{1,4})([\d\s\-]+)", original)
    if match:
        cc = match.group(1)
        rest = match.group(2)
    else:
        cc = ""
        rest = re.sub(r"[^\d]", "", original)

    # Pattern 1: original
    pattern1 = original

    # Pattern 2: remove country code, keep original formatting
    pattern2 = re.sub(rf"^\+?{cc}\s*", "", original)

    # Pattern 3: 0 + pattern 2
    pattern3 = "0" + pattern2

    # Pattern 4: remove space/hyphen from pattern 2
    pattern4 = re.sub(r"[\s\-]", "", pattern2)

    # Pattern 5: remove space/hyphen from original
    pattern5 = re.sub(r"[\s\-]", "", original)

    # Pattern 6: 0 + pattern 4
    pattern6 = "0" + pattern4

    return [pattern1, pattern2, pattern3, pattern4, pattern5, pattern6]

def format_outputs(business, patterns):
    # Output 1
    out1 = f'{business} "{patterns[0]}"'

    # Output 2: original, pattern2, pattern5
    out2 = f'{business} "{patterns[0]}" OR "{patterns[1]}" OR "{patterns[4]}"'

    # Output 3: all 6
    all_patterns = ' OR '.join(f'"{p}"' for p in patterns)
    out3 = f"{business} {all_patterns}"

    return out1, out2, out3

# Streamlit UI
st.set_page_config(page_title="Web Search Pattern Generator", layout="centered")
st.title("🌐 Web Search")

with st.form("pattern_form"):
    business = st.text_input("Enter Name")
    phone = st.text_input("Enter Phone Number (e.g., +91 72870-62455)")
    submitted = st.form_submit_button("Generate")

if submitted:
    if not business or not phone:
        st.warning("⚠️ Please enter both Name and Phone Number.")
    else:
        patterns = clean_number_patterns(phone)
        out1, out2, out3 = format_outputs(business, patterns)

        st.markdown("---")
        # st.subheader("📌 Output 1: Name + Original Number")
        st.code(out1)

        #st.subheader("📌 Output 2: Name + 3 Combinations (OR)")
        st.code(out2)

     #st.subheader("📌 Output 3: Name + 6 Combinations (OR)")
        st.code(out3)

